# Analise de data/raw/atividades_administrativas.csv

In [1]:
import os
import pandas as pd

In [4]:
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('.')))))
DATA_DIR = os.path.join(BASE_DIR, 'data')
RAW_DIR = os.path.join(DATA_DIR, 'raw')

In [6]:
df = pd.read_csv(os.path.join(RAW_DIR, 'atividades_administrativas.csv'))
df.shape

(90, 7)

In [7]:
df.head()

,id_atividade,data,responsavel,atividade,prioridade,status,tempo_estimado_min
0,15001,2026-07-01,Leonardo Vieira,Gerar relatório,Alta,Concluida,90
1,15002,2026-07-01,Rodrigo Tavares,Organizar arquivos,Alta,Pendente,30
2,15003,2026-07-02,Helena Ferreira,Atualizar cadastro,Alta,Concluida,60
3,15004,2026-07-03,Raquel Mendes,Gerar relatório,Media,Concluida,45
4,15005,2026-07-03,Helena Ferreira,Conferir documentos,Baixa,Pendente,30

In [8]:
df.tail()

,id_atividade,data,responsavel,atividade,prioridade,status,tempo_estimado_min
85,15086,2026-08-28,Hugo Barros,Conferir pagamentos,Baixa,Concluida,120
86,15087,2026-08-28,Raquel Mendes,Atualizar planilha,Alta,Em andamento,30
87,15088,2026-08-29,Renata Moreira,Atender solicitação interna,Baixa,Concluida,15
88,15089,2026-08-30,Thiago Rezende,Conferir pagamentos,Baixa,Concluida,120
89,15090,2026-08-31,Tatiane Rocha,Gerar relatório,Media,Concluida,30

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_atividade        90 non-null     int64
 1   data                90 non-null     str
 2   responsavel         90 non-null     str
 3   atividade           90 non-null     str
 4   prioridade          90 non-null     str
 5   status              90 non-null     str
 6   tempo_estimado_min  90 non-null     int64
dtypes: int64(2), str(5)
memory usage: 5.1 KB

In [12]:
df.duplicated().sum()

np.int64(0)