# Analise de data/raw/colaboradores.csv

In [58]:
import os
import pandas as pd
from pandasql import sqldf

pysqldf = lambda q: sqldf(q, globals())

In [59]:
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('.')))))
DATA_DIR = os.path.join(BASE_DIR, 'data')
RAW_DIR = os.path.join(DATA_DIR, 'raw')

In [60]:
df = pd.read_csv(os.path.join(RAW_DIR, 'colaboradores.csv'))
df.shape

(60, 7)

In [61]:
df.head()

,id_colaborador,nome,departamento,cargo,data_admissao,salario,status
0,1001,Ana Paula Silva,TI,Assistente,2022-01-10,2100,Ativo
1,1002,Bruno Henrique Costa,Compras,Assistente,2022-02-07,1850,Férias
2,1003,Camila Oliveira Santos,Comercial,Auxiliar,2022-03-08,4500,Ativo
3,1004,Daniel Almeida,TI,Assistente,2022-04-05,3800,Ativo
4,1005,Eduardo Martins,Recursos Humanos,Coordenador,2022-05-04,3800,Ativo

In [62]:
df.tail()

,id_colaborador,nome,departamento,cargo,data_admissao,salario,status
55,1056,Samuel Rocha,TI,Assistente,2026-04-27,3800,Ativo
56,1057,Taina Lopes,Financeiro,Auxiliar,2026-05-26,2300,Ativo
57,1058,Vitor Hugo,Compras,Analista,2026-06-23,2300,Ativo
58,1059,Yasmin Alves,Administrativo,Auxiliar,2026-07-22,3200,Férias
59,1060,Wesley Martins,Compras,Analista,2026-08-20,2500,Ativo

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_colaborador  60 non-null     int64
 1   nome            60 non-null     str
 2   departamento    60 non-null     str
 3   cargo           60 non-null     str
 4   data_admissao   60 non-null     str
 5   salario         60 non-null     int64
 6   status          60 non-null     str
dtypes: int64(2), str(5)
memory usage: 3.4 KB

In [64]:
df.duplicated().sum()

np.int64(0)

In [65]:
df.describe()

       id_colaborador      salario
count       60.000000    60.000000
mean      1030.500000  3004.166667
std         17.464249   816.269504
min       1001.000000  1850.000000
25%       1015.750000  2300.000000
50%       1030.500000  2800.000000
75%       1045.250000  3800.000000
max       1060.000000  4500.000000

In [66]:
df.columns

Index(['id_colaborador', 'nome', 'departamento', 'cargo', 'data_admissao',
       'salario', 'status'],
      dtype='str')

In [67]:
q = '''SELECT DISTINCT (status)
            FROM df
'''

pysqldf(q)

     status
0     Ativo
1    Férias
2  Afastado

## Tratamento de dados

In [68]:
df_original = df.copy()

In [69]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_colaborador  60 non-null     int64
 1   nome            60 non-null     str
 2   departamento    60 non-null     str
 3   cargo           60 non-null     str
 4   data_admissao   60 non-null     str
 5   salario         60 non-null     int64
 6   status          60 non-null     str
dtypes: int64(2), str(5)
memory usage: 3.4 KB

In [70]:
df.head()

,id_colaborador,nome,departamento,cargo,data_admissao,salario,status
0,1001,Ana Paula Silva,TI,Assistente,2022-01-10,2100,Ativo
1,1002,Bruno Henrique Costa,Compras,Assistente,2022-02-07,1850,Férias
2,1003,Camila Oliveira Santos,Comercial,Auxiliar,2022-03-08,4500,Ativo
3,1004,Daniel Almeida,TI,Assistente,2022-04-05,3800,Ativo
4,1005,Eduardo Martins,Recursos Humanos,Coordenador,2022-05-04,3800,Ativo

In [71]:
df['id_colaborador'] = df['id_colaborador'].astype('str')
df['salario'] = df['salario'].astype('float')

In [72]:
# remover espaco extras
df.columns = df.columns.str.strip()

In [73]:
# Padronizar letras maiusculas/minusculas
df['nome'] = df['nome'].str.title()
df['departamento'] = df['departamento'].str.title()
df['cargo'] = df['cargo'].str.title()
df['status'] = df['status'].str.title()

In [74]:
# padronizar datas
df['data_admissao'] = pd.to_datetime(df['data_admissao'], errors='coerce', format='%Y-%m-%d')

In [75]:
# campos categoricos
categoricos = [
    'departamento'
    , 'cargo'
    , 'status'
]

In [76]:
for campo in categoricos:
    df[campo] = (
        df[campo]
        .astype('category')
    )

In [77]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_colaborador  60 non-null     str
 1   nome            60 non-null     str
 2   departamento    60 non-null     category
 3   cargo           60 non-null     category
 4   data_admissao   60 non-null     datetime64[us]
 5   salario         60 non-null     float64
 6   status          60 non-null     category
dtypes: category(3), datetime64[us](1), float64(1), str(2)
memory usage: 2.3 KB

In [78]:
df.head()

,id_colaborador,nome,departamento,cargo,data_admissao,salario,status
0,1001,Ana Paula Silva,Ti,Assistente,2022-01-10,2100.0,Ativo
1,1002,Bruno Henrique Costa,Compras,Assistente,2022-02-07,1850.0,Férias
2,1003,Camila Oliveira Santos,Comercial,Auxiliar,2022-03-08,4500.0,Ativo
3,1004,Daniel Almeida,Ti,Assistente,2022-04-05,3800.0,Ativo
4,1005,Eduardo Martins,Recursos Humanos,Coordenador,2022-05-04,3800.0,Ativo