# Analise de data/raw/controle_documentos.csv

In [17]:
import os
import pandas as pd
from pandasql import sqldf

pysqldf = lambda q: sqldf(q, globals())

In [2]:
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('.')))))
DATA_DIR = os.path.join(BASE_DIR, 'data')
RAW_DIR = os.path.join(DATA_DIR, 'raw')

In [3]:
df = pd.read_csv(os.path.join(RAW_DIR, 'controle_documentos.csv'))
df.shape

(120, 7)

In [4]:
df.head()

,id_documento,tipo_documento,descricao,data_recebimento,responsavel,status,local_arquivo
0,11001,Boleto,Processo interno,2026-01-03,Camila Oliveira Santos,Arquivado,Compras
1,11002,Nota Fiscal,Processo interno,2026-01-05,Gisele Moraes,Pendente,Financeiro
2,11003,Boleto,Compra administrativa,2026-01-07,Diego Fernandes,Pendente,RH
3,11004,Nota Fiscal,Documento cliente,2026-01-09,Giovana Lopes,Arquivado,Compras
4,11005,Boleto,Documento cliente,2026-01-11,Thiago Rezende,Conferido,Digital

In [5]:
df.tail()

,id_documento,tipo_documento,descricao,data_recebimento,responsavel,status,local_arquivo
115,11116,Pedido de Compra,Prestação de contas,2026-08-22,Patricia Teixeira,Pendente,Financeiro
116,11117,Contrato,Documento cliente,2026-08-24,Leonardo Vieira,Pendente,Financeiro
117,11118,Pedido de Compra,Processo interno,2026-08-26,Sandra Batista,Pendente,Administrativo
118,11119,Boleto,Compra administrativa,2026-08-28,Yasmin Alves,Conferido,Financeiro
119,11120,Nota Fiscal,Documento fornecedor,2026-08-31,Fernanda Souza,Conferido,Digital

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_documento      120 non-null    int64
 1   tipo_documento    120 non-null    str
 2   descricao         120 non-null    str
 3   data_recebimento  120 non-null    str
 4   responsavel       120 non-null    str
 5   status            120 non-null    str
 6   local_arquivo     120 non-null    str
dtypes: int64(1), str(6)
memory usage: 6.7 KB

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.describe()

       id_documento
count    120.000000
mean   11060.500000
std       34.785054
min    11001.000000
25%    11030.750000
50%    11060.500000
75%    11090.250000
max    11120.000000

In [9]:
df.columns

Index(['id_documento', 'tipo_documento', 'descricao', 'data_recebimento',
       'responsavel', 'status', 'local_arquivo'],
      dtype='str')

In [21]:
q = '''SELECT DISTINCT (tipo_documento)
            FROM df
'''

pysqldf(q)

        tipo_documento
0               Boleto
1          Nota Fiscal
2             Contrato
3     Pedido De Compra
4  Documento Cadastral
5               Recibo
6            Relatorio
7          Comprovante

In [22]:
q = '''SELECT DISTINCT (status)
            FROM df
'''

pysqldf(q)

      status
0  Arquivado
1   Pendente
2  Conferido
3   Recebido

In [23]:
q = '''SELECT DISTINCT (local_arquivo)
            FROM df
'''

pysqldf(q)

    local_arquivo
0         Compras
1      Financeiro
2              Rh
3         Digital
4  Administrativo

## Tratamento de dados

In [10]:
df_original = df.copy()

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_documento      120 non-null    int64
 1   tipo_documento    120 non-null    str
 2   descricao         120 non-null    str
 3   data_recebimento  120 non-null    str
 4   responsavel       120 non-null    str
 5   status            120 non-null    str
 6   local_arquivo     120 non-null    str
dtypes: int64(1), str(6)
memory usage: 6.7 KB

In [14]:
df.head()

,id_documento,tipo_documento,descricao,data_recebimento,responsavel,status,local_arquivo
0,11001,Boleto,Processo interno,2026-01-03,Camila Oliveira Santos,Arquivado,Compras
1,11002,Nota Fiscal,Processo interno,2026-01-05,Gisele Moraes,Pendente,Financeiro
2,11003,Boleto,Compra administrativa,2026-01-07,Diego Fernandes,Pendente,RH
3,11004,Nota Fiscal,Documento cliente,2026-01-09,Giovana Lopes,Arquivado,Compras
4,11005,Boleto,Documento cliente,2026-01-11,Thiago Rezende,Conferido,Digital

In [12]:
df['id_documento'] = df['id_documento'].astype('str')

In [13]:
# removendo espacoes extras
df.columns = df.columns.str.strip()

In [ ]:
# campos title

campos_title = [
    'tipo_documento'
    , 'descricao'
    , 'responsavel'
    , 'status'
    , 'local_arquivo'
]

In [16]:
# Padronizar letras maiusculas/minusculas
for campo in campos_title:
    df[campo] = (
      df[campo].str.title()
        
    )

In [24]:
# campos categoricos

campos_categoricos = [
    'tipo_documento'
   , 'status'
   , 'local_arquivo'
]

In [25]:
# Padronizar campos categoricos

for campo in campos_categoricos:
    df[campo] = (
      df[campo].astype('category')
        
    )

In [27]:
df['data_recebimento'] = pd.to_datetime(df['data_recebimento'], errors='coerce', format='%Y-%m-%d')

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_documento      120 non-null    str
 1   tipo_documento    120 non-null    category
 2   descricao         120 non-null    str
 3   data_recebimento  120 non-null    datetime64[us]
 4   responsavel       120 non-null    str
 5   status            120 non-null    category
 6   local_arquivo     120 non-null    category
dtypes: category(3), datetime64[us](1), str(3)
memory usage: 4.4 KB

In [29]:
df.isna().sum()

id_documento        0
tipo_documento      0
descricao           0
data_recebimento    0
responsavel         0
status              0
local_arquivo       0
dtype: int64

In [30]:
df.head()

,id_documento,tipo_documento,descricao,data_recebimento,responsavel,status,local_arquivo
0,11001,Boleto,Processo Interno,2026-01-03,Camila Oliveira Santos,Arquivado,Compras
1,11002,Nota Fiscal,Processo Interno,2026-01-05,Gisele Moraes,Pendente,Financeiro
2,11003,Boleto,Compra Administrativa,2026-01-07,Diego Fernandes,Pendente,Rh
3,11004,Nota Fiscal,Documento Cliente,2026-01-09,Giovana Lopes,Arquivado,Compras
4,11005,Boleto,Documento Cliente,2026-01-11,Thiago Rezende,Conferido,Digital

## Salvando dados controle documentos em processed

In [31]:
PROCESSED_DIR = os.path.join(DATA_DIR, 'processed')

In [32]:
df.to_csv(os.path.join(PROCESSED_DIR, 'controle_documentos_tratado.csv'), index=False)