# Analise de data/raw/fornecedores.csv

In [20]:
import os
import pandas as pd
from pandasql import sqldf

pysqldf = lambda q: sqldf(q, globals())

In [21]:
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('.')))))
DATA_DIR = os.path.join(BASE_DIR, 'data')
RAW_DIR = os.path.join(DATA_DIR, 'raw')

In [22]:
df = pd.read_csv(os.path.join(RAW_DIR, 'fornecedores.csv'))
df.shape

(20, 6)

In [23]:
df.head()

   id_fornecedor            fornecedor  ... prazo_pagamento_dias   status
0           2001     Papelaria Central  ...                   28    Ativo
1           2002      Office Solutions  ...                    7    Ativo
2           2003         Limpeza Ideal  ...                    7    Ativo
3           2004        Tecno Sistemas  ...                   15  Inativo
4           2005  Transportes Paulista  ...                   45    Ativo

[5 rows x 6 columns]

In [24]:
df.tail()

    id_fornecedor            fornecedor  ... prazo_pagamento_dias   status
15           2016  Correios Empresarial  ...                   45    Ativo
16           2017        RH Consultoria  ...                   28  Inativo
17           2018    Marketing Criativo  ...                   30    Ativo
18           2019        Software Cloud  ...                   30    Ativo
19           2020   Alimentos Bom Sabor  ...                   21    Ativo

[5 rows x 6 columns]

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_fornecedor         20 non-null     int64
 1   fornecedor            20 non-null     str
 2   categoria             20 non-null     str
 3   cidade                20 non-null     str
 4   prazo_pagamento_dias  20 non-null     int64
 5   status                20 non-null     str
dtypes: int64(2), str(4)
memory usage: 1.1 KB

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df.describe()

       id_fornecedor  prazo_pagamento_dias
count       20.00000             20.000000
mean      2010.50000             21.350000
std          5.91608             11.877777
min       2001.00000              7.000000
25%       2005.75000             13.000000
50%       2010.50000             21.000000
75%       2015.25000             28.000000
max       2020.00000             45.000000

In [28]:
df.columns

Index(['id_fornecedor', 'fornecedor', 'categoria', 'cidade',
       'prazo_pagamento_dias', 'status'],
      dtype='str')

In [29]:
q = '''SELECT DISTINCT (status)
            FROM df
'''

pysqldf(q)

    status
0    Ativo
1  Inativo

In [30]:
q = '''SELECT DISTINCT (categoria)
            FROM df
'''

pysqldf(q)

             categoria
0           Transporte
1              Limpeza
2  Material Escritório
3          Alimentação
4             Serviços
5           Tecnologia

## Tratamento de dados

In [31]:
df_original = df.copy()

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_fornecedor         20 non-null     int64
 1   fornecedor            20 non-null     str
 2   categoria             20 non-null     str
 3   cidade                20 non-null     str
 4   prazo_pagamento_dias  20 non-null     int64
 5   status                20 non-null     str
dtypes: int64(2), str(4)
memory usage: 1.1 KB

In [33]:
df.head()

   id_fornecedor            fornecedor  ... prazo_pagamento_dias   status
0           2001     Papelaria Central  ...                   28    Ativo
1           2002      Office Solutions  ...                    7    Ativo
2           2003         Limpeza Ideal  ...                    7    Ativo
3           2004        Tecno Sistemas  ...                   15  Inativo
4           2005  Transportes Paulista  ...                   45    Ativo

[5 rows x 6 columns]

In [34]:
campos_texto = [
    'id_fornecedor'
    , 'fornecedor'
    , 'cidade'
]

In [35]:
for campo in campos_texto:
    df[campo] = (
        df[campo]
        .astype('str')
    )

In [36]:
df.columns = df.columns.str.strip()

In [37]:
campos_categoricos = [
    'categoria'
    , 'status'
]

In [38]:
for campo in campos_categoricos:
    df[campo] = (
        df[campo]
        .astype('category')
    )

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_fornecedor         20 non-null     str
 1   fornecedor            20 non-null     str
 2   categoria             20 non-null     category
 3   cidade                20 non-null     str
 4   prazo_pagamento_dias  20 non-null     int64
 5   status                20 non-null     category
dtypes: category(2), int64(1), str(3)
memory usage: 876.0 bytes

In [40]:
df.head()

  id_fornecedor            fornecedor  ... prazo_pagamento_dias   status
0          2001     Papelaria Central  ...                   28    Ativo
1          2002      Office Solutions  ...                    7    Ativo
2          2003         Limpeza Ideal  ...                    7    Ativo
3          2004        Tecno Sistemas  ...                   15  Inativo
4          2005  Transportes Paulista  ...                   45    Ativo

[5 rows x 6 columns]